services:
  assessment:
    image: assessment_service
    container_name: assessment
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
    depends_on: [db]
  db:
    image: postgres
    container_name: test_paper
    ports:
      - "5432:5432"
    env_file:
      - ".env"