spring:
  application:
    name: Assessment Service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: admin
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

springdoc:
  api-docs:
    path: /api-docs   # Path for the API docs
  swagger-ui:
    path: /swagger-ui.html   # Path for the Swagger UI
    operationsSorter: alpha   # Sort operations alphabetically
    tagsSorter: alpha   # Sort tags alphabetically
